DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS daily_queue CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS produk CASCADE;
DROP TABLE IF EXISTS refresh_tokens CASCADE;
DROP TABLE IF EXISTS auth CASCADE;
